DROP TABLE IF EXISTS locations;
CREATE TABLE locations(
  UUID TEXT NOT NULL,
  LOC_NAME TEXT NOT NULL,
  KIND TEXT NOT NULL,
  STATUS TEXT NOT NULL,
  PRIMARY KEY (UUID),
  UNIQUE (UUID),
  UNIQUE (LOC_NAME)
);
DROP TABLE IF EXISTS nodes;
CREATE TABLE nodes(
  UUID TEXT NOT NULL,
  HOSTNAME TEXT,
  NODE_DOMAIN TEXT,
  LOC_UUID TEXT,
  PRIMARY KEY (UUID),
  UNIQUE (UUID),
  UNIQUE (HOSTNAME),
  FOREIGN KEY (LOC_UUID) REFERENCES locations(UUID)
);
